### ISSUE TITLE
Travis CI with FreeType's version

### ISSUE THREAD

**Issue by cherusker** [freetype/docwriter#2]
Cool, mirroring the repo seems to work well 😃 Just a short note: I think that the build results of FreeType's Travis account (not @nikramakrishnan) should be linked in the [README](https://github.com/freetype/docwriter/blob/master/README.md).

**Comment by cherusker** [comment]
add: same is true for Landscape

**Comment by nikramakrishnan** [comment]
Thanks for reporting! I was busy with the integration and package changes, I'll do this ASAP :-)

**Comment by nikramakrishnan** [comment]
@cherusker I don't have the rights to add Landscape to the organization. 😄

**Comment by cherusker** [comment]
Whooops sorry! 🙈 Fixed!

**Comment by nikramakrishnan** [comment]
Thanks! 😃
