### ISSUE TITLE
Consider using Readme as the long description

### ISSUE THREAD

**Issue by madig** [freetype/docwriter#4]
See https://packaging.python.org/tutorials/packaging-projects/#creating-setup-py

```
[...]
with open("README.md", "r") as fh:
    long_description = fh.read()
[...]
    long_description=long_description,
    long_description_content_type="text/markdown",
```

This will make the Readme render on https://pypi.org/project/docwriter/. Compare with e.g. https://pypi.org/project/black/.

**Comment by nikramakrishnan** [comment]
Ah yes, I'll do this after making a few changes to README. Thanks! 👍
